import { MapPinIcon } from "@heroicons/react/24/outline";

export const provincesInCuba = [
  {
    id: 1,
    name: "La Habana",
    url: "habana",
    color: "bg-indigo-500",
    icon: MapPinIcon,
  },
  {
    id: 13,
    name: "Isla de la Juventud",
    url: "isla-de-la-juventud",
    color: "bg-red-500",
    icon: MapPinIcon,
  },
  {
    id: 14,
    name: "Pinar del Río",
    url: "pinar-del-rio",
    color: "bg-purple-500",
    icon: MapPinIcon,
  },
  {
    id: 15,
    name: "Artemisa",
    url: "artemisa",
    color: "bg-indigo-500",
    icon: MapPinIcon,
  },
  {
    id: 16,
    name: "Mayabeque",
    url: "mayabeque",
    color: "bg-pink-500",
    icon: MapPinIcon,
  },
  {
    id: 2,
    name: "Matanzas",
    url: "matanzas",
    color: "bg-pink-500",
    icon: MapPinIcon,
  },
  {
    id: 3,
    name: "Villa Clara",
    url: "villa-clara",
    color: "bg-blue-500",
    icon: MapPinIcon,
  },
  {
    id: 4,
    name: "Cienfuegos",
    url: "cienfuegos",
    color: "bg-green-500",
    icon: MapPinIcon,
  },
  {
    id: 5,
    name: "Sancti Spíritus",
    url: "sancti-spiritus",
    color: "bg-yellow-500",
    icon: MapPinIcon,
  },
  {
    id: 6,
    name: "Ciego de Ávila",
    url: "ciego-de-avila",
    color: "bg-red-500",
    icon: MapPinIcon,
  },
  {
    id: 7,
    name: "Camagüey",
    url: "camaguey",
    color: "bg-purple-500",
    icon: MapPinIcon,
  },
  {
    id: 8,
    name: "Las Tunas",
    url: "las-tunas",
    color: "bg-indigo-500",
    icon: MapPinIcon,
  },
  {
    id: 9,
    name: "Holguín",
    url: "holguin",
    color: "bg-pink-500",
    icon: MapPinIcon,
  },
  {
    id: 10,
    name: "Granma",
    url: "granma",
    color: "bg-blue-500",
    icon: MapPinIcon,
  },
  {
    id: 11,
    name: "Santiago de Cuba",
    url: "santiago-de-cuba",
    color: "bg-green-500",
    icon: MapPinIcon,
  },
  {
    id: 12,
    name: "Guantánamo",
    url: "guantanamo",
    color: "bg-yellow-500",
    icon: MapPinIcon,
  },
];
